In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[ 1.39565537, -0.10339678,  1.30832306, ...,  0.09990243,
        -0.09474014, -1.03693141],
       [ 0.18470125,  1.03358027,  0.22420831, ...,  0.71424052,
         0.67256857,  0.27082664],
       [ 2.14461041,  0.65835524,  2.1839542 , ...,  1.96773845,
         1.4830384 ,  0.91035896],
       ...,
       [-1.04920935,  0.11134044, -1.05504709, ..., -0.74465732,
        -0.02760063, -0.37091285],
       [-0.56138423, -1.19516599, -0.61598062, ..., -1.50234097,
        -0.97075092, -1.31503692],
       [-0.35477594, -0.77925391, -0.3453689 , ..., -0.21967749,
         1.03704021, -0.1667481 ]])

In [10]:
y_train

127    M
65     M
393    M
338    B
367    B
      ..
545    B
307    B
245    B
316    B
143    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0])

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [34]:
X_train_tensor = X_train_tensor.to(dtype = torch.float32)

In [35]:
y_train_tensor = y_train_tensor.to(dtype = torch.float32)

In [43]:
X_test_tensor = X_test_tensor.to(dtype = torch.float32)

In [44]:
y_test_tensor = y_test_tensor.to(dtype = torch.float32)

In [36]:
class MySimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype = torch.float32, requires_grad = True)
    self.bias = torch.zeros(1, dtype = torch.float32, requires_grad  = True)

  def forward(self,X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1- epsilon)

    loss = - (y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss

In [37]:
learning_rate = 0.1
epochs = 25

In [38]:
# Create Model
model = MySimpleNN(X_train_tensor)

# define loops

for epoch in range(epochs):

  # Forward Pass
  y_pred = model.forward(X_train_tensor)

  # Calculate Loss
  loss = model.loss_function(y_pred, y_train_tensor)

  print(f"Epoch : {epoch + 1}, Loss: {loss.item()}")

  # Backward pass

  loss.backward()

  # Parameter Updates
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()

Epoch : 1, Loss: 3.665682792663574
Epoch : 2, Loss: 3.532775640487671
Epoch : 3, Loss: 3.395549774169922
Epoch : 4, Loss: 3.252314329147339
Epoch : 5, Loss: 3.104795217514038
Epoch : 6, Loss: 2.9547505378723145
Epoch : 7, Loss: 2.8022327423095703
Epoch : 8, Loss: 2.6442432403564453
Epoch : 9, Loss: 2.4848504066467285
Epoch : 10, Loss: 2.3173630237579346
Epoch : 11, Loss: 2.146186113357544
Epoch : 12, Loss: 1.9786874055862427
Epoch : 13, Loss: 1.8041837215423584
Epoch : 14, Loss: 1.6332740783691406
Epoch : 15, Loss: 1.4724681377410889
Epoch : 16, Loss: 1.3245056867599487
Epoch : 17, Loss: 1.1920039653778076
Epoch : 18, Loss: 1.0774561166763306
Epoch : 19, Loss: 0.9827792644500732
Epoch : 20, Loss: 0.9087308049201965
Epoch : 21, Loss: 0.8543749451637268
Epoch : 22, Loss: 0.8168144822120667
Epoch : 23, Loss: 0.7918294668197632
Epoch : 24, Loss: 0.7752858400344849
Epoch : 25, Loss: 0.7640417218208313

In [40]:
model.weights

tensor([[-0.1121],
        [ 0.0269],
        [ 0.3579],
        [ 0.0388],
        [ 0.2163],
        [-0.5486],
        [-0.5575],
        [ 0.2752],
        [ 0.3548],
        [ 0.0501],
        [-0.3123],
        [ 0.2400],
        [ 0.1759],
        [-0.3110],
        [ 0.1657],
        [-0.3403],
        [-0.2660],
        [ 0.2790],
        [ 0.3139],
        [ 0.1286],
        [ 0.3800],
        [-0.2540],
        [ 0.0189],
        [ 0.4258],
        [-0.1895],
        [ 0.2920],
        [ 0.1102],
        [-0.3961],
        [ 0.3102],
        [ 0.3921]], requires_grad=True)

In [41]:
model.bias

tensor([-0.1315], requires_grad=True)

In [45]:
# Model Evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5366266369819641

In [46]:
type(accuracy)

torch.Tensor

### torch.nn.Module

In [47]:
import torch
import torch.nn as nn

In [48]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [49]:
# Create Dataset

features = torch.rand(10,5)

model = Model(features.shape[1])
model(features)

tensor([[0.4371],
        [0.4041],
        [0.4589],
        [0.5100],
        [0.5282],
        [0.4907],
        [0.4149],
        [0.5598],
        [0.5327],
        [0.4707]], grad_fn=<SigmoidBackward0>)

In [50]:
model.linear.weight

Parameter containing:
tensor([[-0.1274, -0.0125, -0.3902, -0.2443,  0.3547]], requires_grad=True)

In [51]:
model.linear.bias

Parameter containing:
tensor([0.2104], requires_grad=True)

In [52]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [53]:
from torchinfo import summary

In [54]:
summary(model, imput_size=(10,5))

=================================================================
Layer (type:depth-idx)                   Param #
=================================================================
Model                                    --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
=================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
=================================================================

## NN wth Hidden Layer

In [55]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [56]:
# Create Dataset

features = torch.rand(10,5)

model = Model(features.shape[1])
model(features)

tensor([[0.5242],
        [0.5372],
        [0.5349],
        [0.5186],
        [0.4923],
        [0.5319],
        [0.5081],
        [0.5115],
        [0.5165],
        [0.5453]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight.shape

In [ ]:
model.linear1.bias

In [ ]:
model.linear2.weight.shape

In [ ]:
model.linear2.bias

In [ ]:
summary(model, input_size=(10,5))

## Sequential Container

In [57]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)

    return out

In [58]:
# Create Dataset

features = torch.rand(10,5)

model = Model(features.shape[1])
model(features)

tensor([[0.5685],
        [0.5828],
        [0.5690],
        [0.5614],
        [0.5515],
        [0.5612],
        [0.5441],
        [0.5732],
        [0.5915],
        [0.5752]], grad_fn=<SigmoidBackward0>)

## Improving Our Original Task

In [59]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1- epsilon)

    loss = - (y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss

In [60]:
learning_rate = 0.1
epochs = 25

In [63]:
# Create Model
model = MySimpleNN(X_train_tensor.shape[1])

# define loops

for epoch in range(epochs):

  # Forward Pass
  y_pred = model(X_train_tensor)

  # Calculate Loss
  loss = model.loss_function(y_pred, y_train_tensor)

  print(f"Epoch : {epoch + 1}, Loss: {loss.item()}")

  # Backward pass

  loss.backward()

  # Parameter Updates
  with torch.no_grad():
    model.network.linear.weight -= learning_rate * model.network.linear.weight.grad
    model.network.linear.bias -= learning_rate * model.network.linear.bias.grad
  model.network.linear.weight.grad.zero_()
  model.network.linear.bias.grad.zero_()

Epoch : 1, Loss: 0.7351486086845398

AttributeError: 'Sequential' object has no attribute 'linear'