In [102]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [103]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [104]:
df.shape

(569, 33)

In [105]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [106]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [107]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [108]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [109]:
X_train

array([[-1.20703261, -0.26623308, -1.12997188, ..., -0.18237111,
        -0.4460118 ,  1.94856285],
       [-1.35432523,  0.57502177, -1.33393033, ..., -1.32250542,
        -0.84041823,  0.52628927],
       [-0.69397786,  0.18925297, -0.68378648, ..., -0.46018766,
         0.53503278,  0.37545992],
       ...,
       [-0.11003672, -0.66826924, -0.1560177 , ..., -0.36954807,
        -0.12783518, -0.31269896],
       [-1.17042735,  0.48206544, -1.18926702, ..., -1.32017735,
        -0.88516182, -0.14831854],
       [-0.75789181,  0.41002427, -0.74266109, ..., -0.76951079,
        -0.20075065,  0.31713139]])

In [110]:
y_train

176    B
412    B
531    B
284    B
517    M
      ..
221    B
426    B
532    B
425    B
80     B
Name: diagnosis, Length: 455, dtype: object

In [111]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [112]:
y_train

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [113]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [114]:
X_train_tensor = X_train_tensor.to(dtype = torch.float32)

In [115]:
y_train_tensor = y_train_tensor.to(dtype = torch.float32)

In [116]:
X_test_tensor = X_test_tensor.to(dtype = torch.float32)

In [117]:
y_test_tensor = y_test_tensor.to(dtype = torch.float32)

In [118]:
class MySimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype = torch.float32, requires_grad = True)
    self.bias = torch.zeros(1, dtype = torch.float32, requires_grad  = True)

  def forward(self,X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1- epsilon)

    loss = - (y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss

In [119]:
learning_rate = 0.1
epochs = 25

In [120]:
# Create Model
model = MySimpleNN(X_train_tensor)

# define loops

for epoch in range(epochs):

  # Forward Pass
  y_pred = model.forward(X_train_tensor)

  # Calculate Loss
  loss = model.loss_function(y_pred, y_train_tensor)

  print(f"Epoch : {epoch + 1}, Loss: {loss.item()}")

  # Backward pass

  loss.backward()

  # Parameter Updates
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()

Epoch : 1, Loss: 4.018110752105713
Epoch : 2, Loss: 3.920776844024658
Epoch : 3, Loss: 3.8170835971832275
Epoch : 4, Loss: 3.709214687347412
Epoch : 5, Loss: 3.594923257827759
Epoch : 6, Loss: 3.4736928939819336
Epoch : 7, Loss: 3.347825765609741
Epoch : 8, Loss: 3.2160305976867676
Epoch : 9, Loss: 3.08394455909729
Epoch : 10, Loss: 2.9482524394989014
Epoch : 11, Loss: 2.807778835296631
Epoch : 12, Loss: 2.6664021015167236
Epoch : 13, Loss: 2.520866632461548
Epoch : 14, Loss: 2.3740038871765137
Epoch : 15, Loss: 2.220834970474243
Epoch : 16, Loss: 2.0662918090820312
Epoch : 17, Loss: 1.915855884552002
Epoch : 18, Loss: 1.773532509803772
Epoch : 19, Loss: 1.6367945671081543
Epoch : 20, Loss: 1.510357141494751
Epoch : 21, Loss: 1.394359827041626
Epoch : 22, Loss: 1.2849886417388916
Epoch : 23, Loss: 1.1887412071228027
Epoch : 24, Loss: 1.107500433921814
Epoch : 25, Loss: 1.040558099746704

In [121]:
model.weights

tensor([[ 0.3617],
        [ 0.1960],
        [-0.1852],
        [ 0.4703],
        [ 0.2635],
        [-0.0048],
        [ 0.1791],
        [-0.0777],
        [ 0.3277],
        [ 0.3427],
        [-0.2255],
        [ 0.4668],
        [-0.3458],
        [-0.0665],
        [ 0.3659],
        [-0.2254],
        [ 0.1767],
        [ 0.2684],
        [ 0.7217],
        [ 0.2514],
        [-0.0175],
        [-0.1147],
        [-0.0187],
        [ 0.2015],
        [ 0.0856],
        [-0.1326],
        [ 0.0471],
        [-0.2545],
        [ 0.2755],
        [-0.0532]], requires_grad=True)

In [122]:
model.bias

tensor([-0.1472], requires_grad=True)

In [123]:
# Model Evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5120037198066711

In [124]:
type(accuracy)

torch.Tensor

### torch.nn.Module

In [125]:
import torch
import torch.nn as nn

In [126]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [127]:
# Create Dataset

features = torch.rand(10,5)

model = Model(features.shape[1])
model(features)

tensor([[0.4102],
        [0.5401],
        [0.5075],
        [0.4269],
        [0.5023],
        [0.4237],
        [0.3691],
        [0.4905],
        [0.4844],
        [0.4429]], grad_fn=<SigmoidBackward0>)

In [128]:
model.linear.weight

Parameter containing:
tensor([[ 0.2327, -0.0706,  0.3126, -0.2384, -0.4264]], requires_grad=True)

In [129]:
model.linear.bias

Parameter containing:
tensor([-0.1029], requires_grad=True)

In [130]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [131]:
from torchinfo import summary

In [132]:
summary(model, imput_size=(10,5))

=================================================================
Layer (type:depth-idx)                   Param #
=================================================================
Model                                    --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
=================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
=================================================================

## NN wth Hidden Layer

In [133]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [134]:
# Create Dataset

features = torch.rand(10,5)

model = Model(features.shape[1])
model(features)

tensor([[0.6237],
        [0.6396],
        [0.6575],
        [0.6938],
        [0.6903],
        [0.6694],
        [0.6506],
        [0.6967],
        [0.6503],
        [0.5933]], grad_fn=<SigmoidBackward0>)

In [135]:
model.linear1.weight.shape

torch.Size([3, 5])

In [136]:
model.linear1.bias

Parameter containing:
tensor([-0.2949, -0.0822, -0.1750], requires_grad=True)

In [137]:
model.linear2.weight.shape

torch.Size([1, 3])

In [138]:
model.linear2.bias

Parameter containing:
tensor([0.3394], requires_grad=True)

In [139]:
summary(model, input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

## Sequential Container

In [140]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
    nn.Linear(num_features, 3),
    nn.ReLU(),
    nn.Linear(3, 1),
    nn.Sigmoid())

  def forward(self, features):
    out = self.network(features)

    return out

In [141]:
# Create Dataset

features = torch.rand(10,5)

model = Model(features.shape[1])
model(features)

tensor([[0.5028],
        [0.4890],
        [0.4891],
        [0.4960],
        [0.4890],
        [0.4881],
        [0.5075],
        [0.5027],
        [0.4899],
        [0.4901]], grad_fn=<SigmoidBackward0>)

## Improving Our Original Task

In [142]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [143]:
learning_rate = 0.1
epochs = 25

In [144]:
loss_function = nn.BCELoss()

### Batch Gradient Descent

In [145]:
# Create Model
model = Model(X_train_tensor.shape[1])

# define loops
# Define optimizer

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

#Batch Gradient Descent -- Slower Convergence
for epoch in range(epochs):

  # Forward Pass
  y_pred = model(X_train_tensor)

  # Calculate Loss
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # Clear Gradients
  optimizer.zero_grad()

  # Backward pass

  loss.backward()

  # Parameter Update
  optimizer.step()

  print(f"Epoch : {epoch + 1}, Loss: {loss.item()}")

Epoch : 1, Loss: 0.8237110376358032
Epoch : 2, Loss: 0.5920508503913879
Epoch : 3, Loss: 0.47685518860816956
Epoch : 4, Loss: 0.41064009070396423
Epoch : 5, Loss: 0.36680543422698975
Epoch : 6, Loss: 0.3351467549800873
Epoch : 7, Loss: 0.3109455406665802
Epoch : 8, Loss: 0.29169145226478577
Epoch : 9, Loss: 0.27591198682785034
Epoch : 10, Loss: 0.2626802623271942
Epoch : 11, Loss: 0.25138047337532043
Epoch : 12, Loss: 0.24158596992492676
Epoch : 13, Loss: 0.23299074172973633
Epoch : 14, Loss: 0.22536900639533997
Epoch : 15, Loss: 0.2185501605272293
Epoch : 16, Loss: 0.21240271627902985
Epoch : 17, Loss: 0.20682339370250702
Epoch : 18, Loss: 0.20172984898090363
Epoch : 19, Loss: 0.19705557823181152
Epoch : 20, Loss: 0.192746102809906
Epoch : 21, Loss: 0.1887565404176712
Epoch : 22, Loss: 0.18504919111728668
Epoch : 23, Loss: 0.18159246444702148
Epoch : 24, Loss: 0.17835944890975952
Epoch : 25, Loss: 0.1753271520137787

In [146]:
for param in model.parameters():
  print(param)

Parameter containing:
tensor([[ 0.3105,  0.0790,  0.1250,  0.2015,  0.1601,  0.2473,  0.1650,  0.1727,
          0.0229, -0.1076,  0.2804,  0.0523,  0.2812,  0.1953, -0.1521, -0.0322,
         -0.0212,  0.1739,  0.0148, -0.1760,  0.2973,  0.3478,  0.2838,  0.1561,
          0.1831,  0.0724,  0.1228,  0.1689,  0.2341,  0.2320]],
       requires_grad=True)
Parameter containing:
tensor([-0.1915], requires_grad=True)

In [147]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5193905830383301

### Mini Batch GD

In [148]:
# Mini-Batch GD

batch_size = 32
epochs = 25
n_samples = len(X_train_tensor)

for epoch in range(epochs):
  #Loop over the dataset in chunks of "batch_size"
  for start_idx in range(0, n_samples, batch_size):
    end_idx = start_idx + batch_size
    X_batch = X_train_tensor[start_idx:end_idx]
    y_batch = y_train_tensor[start_idx:end_idx]

    y_pred = model(X_batch)
    loss = loss_function(y_pred, y_batch.view(-1,1))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  print(f"Epoch : {epoch + 1}, Loss: {loss.item()}")

Epoch : 1, Loss: 0.11594242602586746
Epoch : 2, Loss: 0.0910138338804245
Epoch : 3, Loss: 0.0757526382803917
Epoch : 4, Loss: 0.06537683308124542
Epoch : 5, Loss: 0.05783220753073692
Epoch : 6, Loss: 0.052082233130931854
Epoch : 7, Loss: 0.047544509172439575
Epoch : 8, Loss: 0.043865662068128586
Epoch : 9, Loss: 0.04081839695572853
Epoch : 10, Loss: 0.03824962303042412
Epoch : 11, Loss: 0.036052409559488297
Epoch : 12, Loss: 0.03414970263838768
Epoch : 13, Loss: 0.03248453885316849
Epoch : 14, Loss: 0.031013930216431618
Epoch : 15, Loss: 0.029704729095101357
Epoch : 16, Loss: 0.0285310298204422
Epoch : 17, Loss: 0.027472227811813354
Epoch : 18, Loss: 0.02651176042854786
Epoch : 19, Loss: 0.025636151432991028
Epoch : 20, Loss: 0.024834278970956802
Epoch : 21, Loss: 0.024096950888633728
Epoch : 22, Loss: 0.0234164260327816
Epoch : 23, Loss: 0.02278621681034565
Epoch : 24, Loss: 0.02220076695084572
Epoch : 25, Loss: 0.02165534533560276

### Read Dataset and DataLoader notebook and then proceed

In [149]:
from torch.utils.data import Dataset, DataLoader

In [150]:
class CustomDataset(Dataset):

  def __init__(self,features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  # We can make any transformations here in this method before returning item
  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [151]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [152]:
train_dataset[3]

(tensor([-0.3395, -0.8147, -0.3108, -0.3794, -1.2824, -0.1334,  0.3471, -0.3566,
         -1.4075, -0.4930, -0.3970,  0.3339, -0.2403, -0.3539, -0.1953,  0.8841,
          1.8810,  1.0275, -0.2220, -0.0131, -0.4764, -0.9422, -0.4321, -0.4844,
         -1.4190, -0.0928,  0.3844, -0.1420, -1.4652, -0.6986]),
 tensor(0.))

In [153]:
train_loader = DataLoader(train_dataset, batch_size = 32, shuffle = True)
test_loader = DataLoader(test_dataset, batch_size = 32, shuffle = True)

## Defining Model

In [154]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

## Important Parameters

In [155]:
learning_rate = 0.1
epochs = 25

In [156]:
# Creating model
model = Model(X_train_tensor.shape[1])

# Define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

# Define Loss Function
loss_funciton = nn.BCELoss()

## Training pipeline

In [157]:
for epoch in range(epochs):
  for batch_features, batch_labels in train_loader:
    y_pred = model(batch_features)
    loss = loss_function(y_pred,batch_labels.view(-1,1))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
  print(f"Epoch : {epoch + 1}, Loss: {loss.item()}")

Epoch : 1, Loss: 0.3129069209098816
Epoch : 2, Loss: 0.1242431029677391
Epoch : 3, Loss: 0.19675244390964508
Epoch : 4, Loss: 0.0369434729218483
Epoch : 5, Loss: 0.057844605296850204
Epoch : 6, Loss: 0.041948411613702774
Epoch : 7, Loss: 0.24320796132087708
Epoch : 8, Loss: 0.07917729765176773
Epoch : 9, Loss: 0.03993165120482445
Epoch : 10, Loss: 0.32272201776504517
Epoch : 11, Loss: 0.09924216568470001
Epoch : 12, Loss: 0.024339836090803146
Epoch : 13, Loss: 0.07628946751356125
Epoch : 14, Loss: 0.01321425475180149
Epoch : 15, Loss: 0.23931053280830383
Epoch : 16, Loss: 0.004180776420980692
Epoch : 17, Loss: 0.057801876217126846
Epoch : 18, Loss: 0.013414854183793068
Epoch : 19, Loss: 0.016524460166692734
Epoch : 20, Loss: 0.045611459761857986
Epoch : 21, Loss: 0.01146265584975481
Epoch : 22, Loss: 0.07789874821901321
Epoch : 23, Loss: 0.0405903123319149
Epoch : 24, Loss: 0.01880638860166073
Epoch : 25, Loss: 0.012039397843182087

## Evaluation

In [160]:
model.eval()
accuracy_list = []
with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    print("Shape of bacth labels : ",batch_labels.shape)
    y_pred = model(batch_features)
    print("Shape of predicted labels : ", y_pred.shape)
    y_pred = (y_pred > 0.8).float()
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy : {overall_accuracy:.4f}')

Shape of bacth labels :  torch.Size([32])
Shape of predicted labels :  torch.Size([32, 1])
Shape of bacth labels :  torch.Size([32])
Shape of predicted labels :  torch.Size([32, 1])
Shape of bacth labels :  torch.Size([32])
Shape of predicted labels :  torch.Size([32, 1])
Shape of bacth labels :  torch.Size([18])
Shape of predicted labels :  torch.Size([18, 1])
Accuracy : 0.9688